# -*- coding: utf-8 -*-
"""pythonbasic

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KlY98lxp_PfDfnZNGiawlYcQdBFgllgB
"""

"HEllo World"

5+10

print("Welcome to Excelr!")

5+20

marks=80
marks

type(marks)

5**4

price=50.5
print(price) #only show o/p of last line 
type(price)

name="Chetan"
type(name)

dir(str) #all method  that can be applied on strins
#dunder/magic methods (double underscore methods which python uses internally python)

str1="Welcome to Data Science "
str1.capitalize()

str1.upper()

str1.lower()

str1.title()

food="bIryAnI"
name="ChetAn"
print(food.swapcase())
name.swapcase()

s1="My name is Chetan"
print(s1.split()) #list of strings is created
s2="Nashik-Pune-Nashik"
s2.split("-") #- dash is campalsurry

mail="chetankopare11@gmail.com"
mail.split("@")

s1.replace("Chetan","MMayur")

city="Satara"
city.count("a")

"satara".count("a")

name="Ram","Sita"
name*7

n1=5
n1*5

name="Mayur"
surname="Kopare"
name +  surname #concatnates without space

name+ "   "+surname #concatnate with space

"""Welcome to Excelr

"""